// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC34yamkgFJSPPopyDXSA5sEO2Iebat_00',
    appId: '1:521338322289:android:0b527ab5a8395440164ad0',
    messagingSenderId: '521338322289',
    projectId: 'blooddonation-2c67c',
    storageBucket: 'blooddonation-2c67c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ZNaZgtdZI5pnNBcp7uWzcX9I8x6PUew',
    appId: '1:521338322289:ios:8c9e9ba4d441a634164ad0',
    messagingSenderId: '521338322289',
    projectId: 'blooddonation-2c67c',
    storageBucket: 'blooddonation-2c67c.firebasestorage.app',
    androidClientId: '521338322289-j342kodba90al6i99b84gm3ij4dcunmv.apps.googleusercontent.com',
    iosClientId: '521338322289-mu34jt8gtlsmhf7ungijbojnl13kmuop.apps.googleusercontent.com',
    iosBundleId: 'com.example.assessmentFlutterInterview',
  );
}
